python src/tester.py ATaleOfThreeCities.connect submission/prajit/taleofthreecitites.py
python src/tester.py AdditionGame.getMaximumPoints submission/prajit/AdditionGame.py
python src/tester.py ChristmasTreeDecoration.solve submission/prajit/ChristmasTree.py
python src/tester.py NonCoprimeGraph.distance submission/prajit/noncoprimegraph.py
python src/tester.py AdditionGame.getMaximumPoints submission/diptayan/py1-AdditionGame.py
python src/tester.py ChristmasTreeDecoration.solve submission/diptayan/py1-ChristmasTreeDecoration.py
python src/tester.py NonCoprimeGraph.distance submission/diptayan/py1-NonCoprimeGraph.py
python src/tester.py RandomPancakeStack.expectedDeliciousness submission/diptayan/py1-RandomPancakeStack.py
python src/tester.py ATaleOfThreeCities.connect submission/diptayan/py2-ATaleOfThreeCities.py
python src/tester.py NonCoprimeGraph.distance submission/riyanka/py1-NonCoprimeGraph.py
python src/tester.py AdditionGame.getMaximumPoints submission/rwik/py1-AdditionGame.py
