"TABLE contains a dictionary whose rhs is signature and lhs is solution file"""

TABLE = {'ChristmasTreeDecoration.solve':['py1-ChristmasTreeDecoration.sol.txt', 10], 
'NonCoprimeGraph.distance':['py1-NonCoprimeGraph.sol.txt', 10], 
'MealPlan.countDistinct':['py1-MealPlan.sol.txt', 10],
'RandomPancakeStack.expectedDeliciousness':['py1-RandomPancakeStack.sol.txt', 10], 
'AdditionGame.getMaximumPoints' : ['py1-AdditionGame.sol.txt', 10], 
'ATaleOfThreeCities.connect' : ['py2-ATaleOfThreeCities.sol.txt', 10], 
'CrossWord.countWords' : ['', 10], 
'IntoTheMatrix.takePills' : ['', 10], 
'EventOrder.getCount' : ['', 10], 
'Abacus.add' : ['', 10],
'AccountBalance.processTransactions' : ['', 10],
'WordFind.findWords' : ['', 10], 
'OddEvenTree.getTree' : ['py1-OddEvenTree.sol.txt', 10], 
'RepeatedSubstrings.decompress' : ['py1-RepeatedSubstrings.sol.txt', 10],
'Spanning.cost' : ['py2-Spanning.sol.txt', 10],
'ImprovingStatistics.howManyGames':['py1-ImprovingStatistics.sol.txt', 10],
'RandomWalkonGrid.getExpectation':['py1-RandomWalkOnGrid.sol.txt', 10],
'ShiftBricks.get':['py1-ShiftBricks.sol.txt', 10]}
